- id: doi:10.3929/ETHZ-B-000409193
  remove: true
- id: doi:10.3929/ethz-b-000304530
  remove: true
- id: doi: 10.26050/WDCC/FESOM14-RECOM2_A_HIST_VA_VC
  remove: true
- id: doi: 10.26050/WDCC/FESOM14-RECOM2_A_S126_VA_VC
  remove: true
- id: doi: 10.26050/WDCC/FESOM14-RECOM2_A_S245_VA_VC
  remove: true
- id: doi: 10.26050/WDCC/FESOM14-RECOM2_A_S370_VA_VC
  remove: true
- id: doi: 10.26050/WDCC/FESOM14-RECOM2_A_S585_VA_VC
  remove: true
- id: doi: 10.26050/WDCC/FESOM14-RECOM2_B_1921_CA_CC
  remove: true
- id: doi: 10.26050/WDCC/FESOM14-RECOM2_C_HIST_CA_CC
  remove: true
- id: doi: 10.26050/WDCC/FESOM14-RECOM2_C_S245_CA_CC
  remove: true
- id: doi: 10.26050/WDCC/FESOM14-RECOM2_C_S585_CA_CC
  remove: true
- id: doi: 10.26050/WDCC/FESOM14-RECOM2_D_HIST_CA_VC
  remove: true
- id: doi: 10.26050/WDCC/FESOM14-RECOM2_D_S585_CA_VC
  remove: true
- id: doi: 10.3929/ETHZ-B-000351758
  remove: true
